import os.path

Import("java_lib", "java_jar", "env")


def BuildJavaTest(env, dir):
	app = env.Java(dir, dir)
	lib_link = env.Symlink(os.path.join(dir, "libhaiku-onJava.so"), java_lib)
	jar_link = env.Symlink(os.path.join(dir, "haiku.jar"), java_jar)
	env.Depends(app, jar_link)
	env.Depends(app, lib_link)

javaEnv = env.Clone()
javaEnv.Append(JAVACFLAGS = ["-cp", java_jar])

BuildJavaTest(javaEnv, "handler/")
BuildJavaTest(javaEnv, "gui/")
